complexity: 1
config: '5116'
dataset: mediapipe-xset
dataset_args:
  mediapipe:
    eval_batch_size: 8
    inputs: JVB
    mediapipe_path: ./data/mediapipe
    ntu120_path: ./data/ntu120
    ntu60_path: ./data/ntu60
    num_frame: 144
    root_folder: ./data/npy_dataset
    train_batch_size: 8
    transform: false
debug: false
delay_hours: 0
evaluate: false
extract: false
fps: 15
generate_data: false
generate_skeleton_file: false
gpus:
- 0
label: 0
lr_scheduler: cosine
model_args:
  act_type: swish
  att_type: stja
  bias: true
  block_args:
  - - 48
    - 1
    - 0.5
  - - 24
    - 1
    - 0.5
  - - 64
    - 2
    - 1
  - - 128
    - 2
    - 1
  drop_prob: 0.25
  edge: true
  expand_ratio: 0
  fusion_stage: 2
  kernel_size:
  - 5
  - 2
  layer_type: SG
  reduct_ratio: 2
  scale_args:
  - 1.2
  - 1.35
  stem_channel: 64
model_type: EfficientGCN-B4
no_progress_bar: false
optimizer: SGD
optimizer_args:
  Adam:
    betas:
    - 0.9
    - 0.99
    lr: 0.1
    weight_decay: 0.0001
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0001
pretrained_path: ./data
resume: false
runner: true
scheduler_args:
  cosine:
    max_epoch: 30
    warm_up: 10
  step:
    max_epoch: 30
    step_lr:
    - 20
    - 50
    warm_up: 10
seed: 1
short_side: 480
video: videos/tmp
visualization_class: 0
visualization_frames: []
visualization_sample: 0
visualize: false
visualize_skeleton: false
work_dir: ./workdir
